### ISSUE TITLE
Some tests returning timeout Errors

### ISSUE THREAD

**Issue by nl-ria** [philippschulte/fastly-promises#1]
Hi, 
I work with the Financial Times and am a  strong advocate of using WAF across all of our services on Fastly. We already use WAF quite extensively here and thus I am eager to extend this repo's functionality to WAF API endpoints as well. 

I have recently forked this repo to add some endpoints for WAF API. I ran the commands to run the existing set of tests but the following 2 are failing stopping me from committing my changes to my fork  :

```
1. purgeKeys
2. updateBackend 
```
Error:

```"before all" hook failed

"before all" hook failed

"before all" hook failed

"before all" hook failed

"before all" hook failed

Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

Any ideas/ ETA on resolving this? I really think this is an excellent library and would greatly simplify my current project. A simplified API  would go a long way to encourage WAFs widespread use.

**P.S. Excellent documentation and a brilliant piece of code. I have already managed to add a couple of endpoints today and I am only a novice Node.js programmer!**

P.P.S.    @cuddlesec - have you seen this ? Thinking of replacing the shell script with this one. :)
Thanks, 
Nikita

**Comment by Limess** [comment]
This is due to an axios dependency update (`follow-redirects` to `1.3`), see https://github.com/olalonde/follow-redirects/issues/77.

Fixed by https://github.com/node-nock/nock/issues/1047 https://github.com/node-nock/nock/releases/tag/v9.1.6

I'd suggest [adding a `package-lock.json` file](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/) to this repository in order to avoid this happening again.

**Comment by philippschulte** [comment]
@nl-ria first of all thanks for using the `fastly-promises` library! @Limess thanks for looking into and solving the issue! However, I am really confused why this was happening because I haven't defined any version ranges of the dependencies! @Limess I'll follow your recommendation and add a `package-lock.json` file to the package.

@nl-ria I am looking forward to your pull requests for the WAF API! Please run:

```bash
$ npm run commit
```
when you commit your changes.

Also please let me know if you need help with adding more endpoints to the library. Just create an issue with any endpoints you need support for!
